### ISSUE TITLE
Assigning commits

### ISSUE THREAD

**Issue by NicolasFrossard** [BenRomberg/cordonbleu#10]
Hi Ben, as we discussed I'd like to work on your idea of a new feature: assigning commits to user. Here is a description of an MVP, let me know what you think so I can begin :)

- Above the commit list there's a new button "Assign Commits" next to the "Show Approved" checkbox
  - Upon click, the commits in the list become selectable (same look and feel as e.g. repository selection). Other UI parts (repository/author selection, commit details) become read-only
  - Also, three buttons appear at the bottom of the commit list: "Cancel", "Select All", "Unassign" and "Assign To..."
  - Upon click on "Assign To...", a user can be selected
- There is a new column "Assigned To" in the commit list
- There is a new field "Assigned To" in the commit details, next to the author

On the back-end side, I don't see much difficulties, only adding an `Optional<User>` to the `Commit.java` entity and make it persisted/editable.

Next improvement could then be sending an email to the assigned user.

Cheers
Nico

**Comment by BenRomberg** [comment]
Hey @NicolasFrossard, thanks for the interest in contributing to CordonBleu! :-)

A couple of remarks:
* I'd automatically distribute commit assignments. We can still think about allowing manual assignments, but I don't think we'd use it at all since it would take a lot of effort assigning commits to 8 different people.
* I'd position the "Assign commits" button somewhere else. It has nothing to do with filtering commits (where the "Show Approved" checkbox is located). Maybe it's a "team" related action and should be in the "default-team" or "Team Settings" dropdowns, or as a separate button between "Commits" and "Team Settings" (I like that one best)?
* Upon click, I'd just show a dialog with the list of the team members. They all have a checkbox (initially checked) next to them. You then choose all team members currently present in the office. At least 2 team members need to be selected.
* Afterwards, the non-approved (and non-assigned) commits in a certain timeframe (e.g. the last 14 days) of a selected team member get assigned to another random team member that was selected.

I totally agree with your points with the "Assigned to" column and field in the commit details. In addition, I'd add a checkbox "Assigned to me" next to the "Show approved" checkbox that filters the commits which are assigned to me.

What do you think?

**Comment by NicolasFrossard** [comment]
I like your approach, it spares a lot of time and manual effort to automate the assignment that way.

I also like having a separate button between "Commits" and "Team Settings". Reviewing commits and randomly assigning them are two different use cases after all.

One thing we would be missing though is a way to recover in case of mistakes when selecting users to assign to e.g. if a team member who's on vacation was selected and got commits assigned. 

The cheapest solution I see would be to enable (un)assignment on the commit level in the detailed view (right part of the page). One would then unassign commits from the person who was mistakenly selected. It would also gives additional possibilities, like choosing to assign one of your commit to a specific person.

Let me know what you think. I'll then stop talking and start coding :)

**Comment by BenRomberg** [comment]
Sure, sounds good!

**Comment by BenRomberg** [comment]
Merged #11
