### ISSUE TITLE
This project still alive ?

### ISSUE THREAD

**Issue by nicodeur** [BenRomberg/cordonbleu#9]
Hi, 

I would like to know if this project is still alive ?

I asked 2 pull request since 3 month, but nobody respond to them.

Regards,

**Comment by BenRomberg** [comment]
Thanks for your continued interest in CordonBleu.

Sorry about the delay in replying to your PRs, I've been busy otherwise. I just commented on them, but please don't expect regular updates from my side as we're quite happy with the current state of the project.

Feel free to fork the project though if you're unhappy with the project's progress!
